version: '3.8'

services:
  rpncalculator:
    build: ./
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:500
    env_file:
      - ./.env.dev

